### ISSUE TITLE
Kommunicera svarsalternativ till användaren

### ISSUE THREAD

**Issue by einarpersson** [isabelbrandin/Three-in-one-quiz#1]
Bra jobbat! Jag provspelade och när jag fick frågan "Do you want to play another quiz?" så visste jag inte vad jag skulle svara. Ska jag skriva "y" eller "yes"? Jag fick kolla i koden för att veta. Och om jag skrev "y" så stängdes spelet av.

Kommunicera svarsalternativ till användaren. Använd gärna Y / N så slipper man skriva hela ord dessutom.  Här är ett exempel: `Proceed ([y]/n)? `

**PS.** Det kan även vara värt att tänka på fallet då användaren skriver in något helt annat än det du tänkt. Det är särskilt viktigt om det inte är tydligt för användaren vad som förväntas av en. Ska programmet krasha då? Ska man få en ny chans? Ska programmet avslutas men att det kommer ett felmeddelande som säger att man skrev in något olagligt? Vad som är bäst här beror lite på...

**Comment by isabelbrandin** [comment]
Vad gör " Proceed ([y]/n)? " för något? Hur fungerar det?

**Comment by isabelbrandin** [comment]
@einarpersson

**Comment by einarpersson** [comment]
Missförstånd.

`Proceed ....` är inte python-kod utan menades som output till användaren. Inom parantes finns svarsalternativen (`y` eller `n` där jag satt default-värdet (det som händer om man trycker ENTER) till `y`).

Ett annat exempel:
`Är du säker på att du vill avsluta? ([ja ] / nej)`
